config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/auth/github', as: :login
  get '/logout', to: "sessions#destroy"
  get '/auth/github/callback', to: "sessions#create"
  get '/profile', to: "users#show"
end

app/models/event.rb
class Event
  def self.mine(user)
    result = Github.new.activity.events.performed "#{user.screen_name}"
    sorted = result.sort_by { |event| event.created_at }.first(10).reverse

    events = sorted.map do |event_data|
      Event.new(event_data)
    end
  end

  def self.received(user)
    result = Github.new.activity.events.received "#{user.screen_name}"
    sorted = result.sort_by { |event| event.created_at }.first(10).reverse

    events = sorted.map do |event_data|
      Event.new(event_data)
    end
  end

  attr_reader :data, :repo_url, :repo_name, :created_at, :user, :type

  def initialize(data)
    @data       = data
    @repo_url   = "https://github.com/#{data.repo.name}"
    @repo_name  = data.repo.name
    @created_at = data.created_at
    @user = find_user
    @type = get_type(data)
  end

  def find_user
    data.actor.login
  end

  def get_type(info)
    types = {"CreateEvent" => lambda {"Create " + info.payload.ref_type.humanize},
     "PullRequestEvent" => lambda {"Pull Request"},
     "PushEvent" => lambda {"Push"},
     "DeleteEvent" => lambda {"Delete" + info.payload.ref_type.humanize},
     "IssuesEvent" => lambda {"Event" + info.payload.action.humanize}
    }
    types.default = lambda { info.type }
    types[info.type].call
  end
end

app/models/login_data.rb
class LoginData
  attr_accessor :data
  def initialize(data)
    @data = data
  end

  def followers
    raw_info["followers"]
  end

  def following
    raw_info["following"]
  end

  def raw_info
    data["extra"]["raw_info"]
  end
end

app/models/repo.rb
class Repo
  def self.github
    Github.new
  end

  def self.mine(user)
    data = github.repos.list user: "#{user.screen_name}"
    get_params(data) || []
  end

  def self.starred(user)
    data = github.activity.starring.starred user: "#{user.screen_name}"
    get_params(data) || []
  end

  private
  
    def self.get_params(data)
      data.map do |repo|
        { name: repo.name, url: repo.html_url }
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, :screen_name, presence: true

  
 def self.from_omniauth(auth_info)
    user = find_or_create_by(uid: auth_info[:uid])

    user.update_attributes(
      name:               auth_info.extra.raw_info.name,
      screen_name:        auth_info.info.nickname,
      oauth_token:        auth_info.credentials.token,
      #oauth_token_secret: auth_info.credentials.secret
    )
    user
 end
end

app/models/user_presenter.rb
require  'open-uri'
class UserPresenter 
  attr_accessor :data, :user, :stats

  def initialize(data, user)
    @data = data
    @user = user
    @stats ||= scrape_stats
  end

  def followers
    raw_info["followers"]
  end

  def following
    raw_info["following"]
  end

  def raw_info
    data["extra"]["raw_info"]
  end

  def avatar
    raw_info["avatar_url"]
  end

  def repos
    Repo.mine(user)
  end

  def starred
    Repo.starred(user)
  end

  def my_events
    Event.mine(user)
  end

  def received_events
    Event.received(user)
  end

  def organizations
    result = Github.new.orgs.list user: "#{user.screen_name}"
    orgs = result.map do |org|
      {name: org.login, url: org["repos_url"]}
    end
    return orgs || []
  end

  def scrape_stats
    doc = Nokogiri::HTML(open("https://github.com/#{user.screen_name}"))
    nums = doc.css('span.contrib-number').children.map { |num| num.text }

    { year_commits: nums.first, 
      longest_streak: nums.second, 
      current_streak: nums.third }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(omni_data)
      session[:user_id] = user.id
      session[:git_data] = omni_data
    end
    redirect_to profile_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
    def omni_data
      request.env["omniauth.auth"]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @presenter = UserPresenter.new(session[:git_data], current_user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">Git Sum</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li id ="inline"> <a class="" href="#about">About</a> </li>
                <% if !current_user %>
                 <li id="inline"> <%= link_to "Log In", login_path %></li>
                <% else %>
                  <li> <%= link_to "Log Out", logout_path, class: "" %></li>
                  <li> <%= link_to "Profile", profile_path, class: "" %></li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/_repo.html.erb
<%= link_to repo[:name], repo[:url], class: "btn btn-default btn-sm" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GithubMock</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Bootstrap Core CSS -->
  <link rel="stylesheet" href="app/assets/stylesheets/bootstrap.min.css" type="text/css">

  <!-- Custom Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="app/assets/stylesheets/font-awesome/css/font-awesome.min.css" type="text/css">

  <!-- Plugin CSS -->
  <link rel="stylesheet" href="css/animate.min.css" type="text/css">

  <!-- Custom CSS -->
  <link rel="stylesheet" href="app/assets/stylesheets/creative.css" type="text/css">
  <link rel="stylesheet" href="app/assets/stylesheets/overrides.css" type="text/css">



</head>
<body id="page-top">
  <%= render partial: "layouts/navbar" %>

<%= yield %>
<%= javascript_include_tag "application" %>

</body>
</html>

app/views/users/show.html.erb
<div id = "user-show">
    <div class = "row dark">
        <div class="small-spacer"></div>
        <div class = "container">
            <div class = "col-md-3">
                <div class="row">
                    <div class = "col-md-12 text-center">
                        <%= image_tag("#{@presenter.avatar}", size: "200x200", class: 'img-circle img-shadow') %>
                    </div>
                </div>
                <div class="row">
                    <div class = "col-md-12">
                        <div class="col-sm-12 text-center underline">
                          <h3>Followers: <%= " #{@presenter.followers}" %></h3>
                        </div>
                        <div class="col-sm-12 text-center underline">
                          <h3>Following: <%= " #{@presenter.following}" %></h3>
                        </div>
                    </div>
                </div>
            </div><!--col-->

            <div class = "col-md-8">
                <div class = "row">
                    <div class = "col-md-6 text-center">
                        <h1><%= current_user.name %></h1>
                    </div>
                    <div class = "col-md-6 text-center">
                        <h1><%= current_user.screen_name %></h1>
                    </div>
                </div>
                <div class="row">
                  <div class="spacer"></div>
                </div>
            </div>

            <div class = "row">
                <div class = "col-md-8 well shadow">
                    <div class = "row">
                        <div class = "col-md-12 text-center">
                            <h2>Contribution Summary</h2>
                        </div>
                    </div>
                    <div class = "row">
                        <div class ="col-md-7 text-right">
                            <h3>Commits (past year):</h3>
                        </div>
                        <div class ="col-md-4">
                            <h3><%= @presenter.stats[:year_commits] %></h3>
                        </div>
                    </div>
                    <div class = "row">
                        <div class ="col-md-7 text-right">
                            <h3>Longest Streak:</h3>
                        </div>
                        <div class ="col-md-4">
                            <h3><%= @presenter.stats[:longest_streak] %></h3>
                        </div>
                    </div>
                    <div class = "row">
                        <div class ="col-md-7 text-right">
                            <h3>Current Streak:</h3>
                        </div>
                        <div class ="col-md-4">
                            <h3><%= @presenter.stats[:current_streak] %></h3>
                        </div>
                    </div>
                </div><!--Contrib summary-->
            </div><!--Row-->
        </div><!--container-->
        <div class="small-spacer"></div>
    </div><!--END ROW-->
        <div class="spacer"></div>
        <div class = "row">
            <div class = "col-md-12 well shadow">
                <div class = "row">
                    <div class = "col-md-12 text-center">
                      <h2>Repositories</h2>
                      <div class="small-spacer"></div>
                    </div>
                    <div class = "col-md-12 text-center">
                        <%= render partial: "layouts/repo", collection: @presenter.repos %>
                    </div>
                </div>
            </div>
        </div>


        <div class="small-spacer"></div>
        <div class = "row">
            <div class = " col-md-1"></div>
            <div class = " col-md-4 well shadow">
                <div class = "row">
                    <div class = "col-md-12 text-center">
                        <h2>Organizations</h2>
                        <div class="small-spacer"></div>
                    </div>
                </div>
                <div class = "row">
                    <div class = "col-md-12 text-center">
                        <%= render partial: "layouts/repo", collection: @presenter.organizations %>
                    </div>
                </div>
            </div>
            <div class="col-md-2"></div>

            <div class="col-md-4 well shadow">
                <div class = "row">
                    <div class = "col-md-12 text-center">
                        <h2>Starred Repositories</h2>
                        <div class="small-spacer"></div>
                    </div>
                    <div class = "col-md-12 text-center">
                      <%= render partial: "layouts/repo", collection: @presenter.starred %>
                    </div>
                </div>
            </div>
        </div><!--Row-->


    <div class="spacer"></div>

    <div class = "row dark">
        <div class="container">
            <div class = "col-md-12">
                <div class = "row">
                    <div id="my-events-btn" class="col-md-12 text-center">
                      <h2><a>My Activity</a></h2>
                    </div>
                </div>
                <div class="small-spacer"></div>
                <div id="my-events" class = "row">
                    <div class="col-md-12 text-center">
                        <table class="table">
                            <tr>
                                <th class="text-center"><h4>Action</h4></th>
                                <th class="text-center"><h4>Repository</h4></th>
                                <th class="text-center"><h4>Time</h4></th>
                            </tr>
                            <% @presenter.my_events.each do |event| %>
                                <tr>
                                    <td><%=event.type %></td>
                                    <td><%= link_to event.repo_name, event.repo_url %></td>
                                    <td><%= time_ago_in_words(event.created_at) + " ago" %></td>
                                </tr>
                            <% end %>
                        </table>
                    </div>
                </div>
            </div>
        </div><!--Col-->
    </div>

    <div class="spacer"></div>

    <div class = "row dark">
        <div class="container">
            <div class = "col-md-12">
                <div class = "row">
                    <div id="following-btn" class="col-md-12 text-center">
                      <h2><a>Following Activity</a></h2>
                    </div>
                </div>
                <div class="small-spacer"></div>
                <div id="following" class="row">
                    <div class = "col-md-12 text-center">
                        <table class="table">
                            <tr>
                                <th class="text-center"><h4>Action</h4></th>
                                <th class="text-center"><h4>User</h4></th>
                                <th class="text-center"><h4>Repository</h4></th>
                                <th class="text-center"><h4>Time</h4></th>
                            </tr>
                            <% @presenter.received_events.each do |event| %>
                                <tr>
                                    <td><%= event.type %></td>
                                    <td><%= event.user %></td>
                                    <td><%= link_to event.repo_name, event.repo_url %></td>
                                    <td><%= time_ago_in_words(event.created_at) + " ago" %></td>
                                </tr>
                            <% end %>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/welcome/index.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner">
            <h1>Git Sum</h1>
            <hr>
            <p>Your Github information Summarized</p>
            <%= link_to "Log in with Github", login_path, class: "btn btn-primary btn-xl page-scroll" %>
        </div>
    </div>
</header>

<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">It's All Here</h2>
                <hr class="light">
                <p class="text-faded">Profile picture, repositories, recent commits. We got you covered.</p>
                <p class="text-faded">All your Github information in one place.</p>
                <p class="text-faded">Save time, save money. (Does that even make sense?)</p>
                <%= link_to "Get Started!", login_path, class: "btn btn-default btn-xl" %>
            </div>
        </div>
    </div>
</section>